module RASN1
  # This modules is a namesapce for all ASN.1 type classes.
  # @author Sylvain Daubert
  module Types
    self.@primitives: untyped

    self.@constructed: untyped

    self.@id2types: untyped

    # Give all primitive types
    # @return [Array<Types::Primitive>]
    def self.primitives: () -> untyped

    # Give all constructed types
    # @return [Array<Types::Constructed>]
    def self.constructed: () -> untyped

    # @private
    # Decode a DER string to extract identifier octets.
    # @param [String] der
    # @return [Array] Return ASN.1 class as Symbol, contructed/primitive as Symbol,
    #                 ID and size of identifier octets
    def self.decode_identifier_octets: (untyped der) -> ::Array[untyped]

    # Give ASN.1 type from a DER string. If ID is unknown, return a {Types::Base}
    # object.
    # @param [String] der
    # @return [Types::Base]
    # @raise [ASN1Error] +tag+ is out of range
    def self.id2type: (untyped der) -> untyped

    # @private Generate cache for {.id2type}
    def self.generate_id2type_cache: () -> untyped

    # Define a new ASN.1 type from a base one.
    # This new type may have a constraint defines on it.
    # @param [Symbol,String] name new type name. Must start with a capital letter.
    # @param [Types::Base] from class from which inherits
    # @param [Module] in_module module in which creates new type (default to {RASN1::Types})
    # @return [Class] newly created class
    # @yieldparam [Object] value value to set to type, or infered at parsing
    # @yieldreturn [Boolean]
    # @since 0.11.0
    # @since 0.12.0 in_module parameter
    # @example
    #   # Define a new UInt32 type
    #   # UInt32 ::= INTEGER (0 .. 4294967295)
    #   RASN1::Types.define_type('UInt32', from: RASN1::Types::Integer) do |value|
    #     (value >= 0) && (value < 2**32)
    #   end
    def self.define_type: (untyped name, from: untyped, ?in_module: untyped) ?{ (?) -> untyped } -> untyped
  end
end
